version: '3.1'

services:
    redis:
        image: 'redis:alpine'
        ports:
            - ${REDIS_PORT}:6379
    
    rebrow:
        image: marian/rebrow
        ports:
            - '${REDIS_UI_PORT}:5001'
        depends_on:
            - redis

    # Select proper database for development. 
    # Postgresql is default. Uncomment MariaDB and *COMMENT* postgres section when necessary!

    # mariadb:
    #     image: 'mariadb:10.6'
    #     working_dir: /application
    #     volumes:
    #         - '.app:/application'
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    #         - MYSQL_DATABASE=${DB_NAME}
    #         - MYSQL_USER=${DB_NAME}
    #         - MYSQL_PASSWORD=${DB_PASS}
    #     ports:
    #         - '${MARIADB_PORT}:3306'

    postgres:
        image: 'postgres:11.1-alpine'
        working_dir: /application
        volumes:
            - '../app:/application'
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - ${POSTGRES_PORT}:5432

    adminer: 
        image: 'adminer:4.8.1-standalone'
        restart: unless-stopped
        environment:
            ADMINER_DEFAULT_SERVER: "postgres"
            # ADMINER_DEFAULT_SERVER: "mariadb"
            ADMINER_DESIGN: "konya"
        ports:
            - ${ADMINER_PORT}:8080

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '../app:/application'
            - './phpdocker/nginx/devcert.crt:/etc/nginx/certs/devcert.crt'
            - './phpdocker/nginx/devcert.key:/etc/nginx/certs/devcert.key'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - ${WEBSERVER_HTTP_PORT}:80
            - ${WEBSERVER_HTTPS_PORT}:443
        depends_on:
            - php-fpm    

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '../app:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        depends_on:
            - redis

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${MAILHOG_PORT}:8025'

    composer:
        image: 'composer/composer:latest'
        command: 'install'
        volumes:
            - '../app:/app'